import Head from 'next/head';
import React from 'react';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';
import { getTodos } from "../lib/prisma";
import "animate.css";

export default async function Home(){

  const todo = await getTodos();
  const parsedTodos = todo ? todo : null;
  return (
    <div className='max-w-screen-lg mx-auto '>
      <main className='w-2/3 mx-auto '>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
	  <header className=''>
          <br></br><br></br><br></br><br></br>
          <h2 className='animate__animated animate__flash animate__delay-0.5s text-center font-bold text-4xl font-semibold select-none grid gap-y-6  '>Vojtech’s Todo app</h2>
          <br></br><br></br>
      </header>
      
        <TodoForm />
        <TodoList data={parsedTodos}/>
      </main>
    </div>
  );
};